name: Export, Unpack, and Publish Power Platform Solution

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Power Platform CLI
      run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - name: Add CLI to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Authenticate with PAC CLI
      run: |
        pac auth create --environment "${{ secrets.POWERPLATFORM_URL }}" --applicationId "${{ secrets.APP_ID }}" --clientSecret "${{ secrets.CLIENT_SECRET }}" --tenant "${{ secrets.TENANT_ID }}" --name githubAuth

    - name: Export Solution
      run: |
        pac solution export --name ExpenseManagmentSystem --path out/ExpenseManagmentSystem.zip --environment "${{ secrets.POWERPLATFORM_URL }}" --overwrite

    - name: Unpack Solution
      run: |
        pac solution unpack --zipFile out/ExpenseManagmentSystem.zip --folder out/solutions/ExpenseManagmentSystem --solutionType Unmanaged --overwrite

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: out/solutions/ExpenseManagmentSystem
        solution-target-folder: src/solutions/ExpenseManagmentSystem
        token: ${{ secrets.GITHUB_TOKEN }}
