name: Export, Unpack, and Publish Power Platform Solution

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Power Platform Tools (CLI path fix)
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Install Power Platform CLI manually
      run: |
        npm install -g pac

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ secrets.POWERPLATFORM_URL }}
        user-name: ${{ secrets.USERNAME }}
        password-secret: ${{ secrets.PASSWORD }}
        solution-name: ExpenseManagmentSystem
        solution-output-file: out/ExpenseManagmentSystem.zip
        working-directory: out

    - name: Unpack Solution
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: out/ExpenseManagmentSystem.zip
        solution-folder: out/solutions/ExpenseManagmentSystem
        solution-type: Unmanaged
        overwrite-files: true

    - name: Publish Solution
      uses: microsoft/powerplatform-actions/publish-solution@v1
      with:
        environment-url: ${{ secrets.POWERPLATFORM_URL }}
        user-name: ${{ secrets.USERNAME }}
        password-secret: ${{ secrets.PASSWORD }}

    - name: Prepare solution changes for check-in into source control
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: out/solutions/ExpenseManagmentSystem
        solution-target-folder: src/solutions/ExpenseManagmentSystem
        token: ${{ secrets.GITHUB_TOKEN }}
