name: Export Power Platform Solution

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Add Power Platform CLI to PATH
      run: |
        echo "##[add-path]$env:USERPROFILE\\AppData\\Local\\Microsoft\\PowerAppsCLI" >> $env:GITHUB_ENV

    - name: Export Solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{ secrets.POWERPLATFORM_URL }}
        tenant-id: ${{ secrets.TENANT_ID }}
        app-id: ${{ secrets.APP_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        solution-name: ExpenseManagmentSystem
        solution-output-file: out/ExpenseManagmentSystem.zip
        working-directory: out
