name: Export, Unpack, and Publish Power Platform Solution

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Power Platform CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          echo "C:\Users\runneradmin\.dotnet\tools" >> $GITHUB_PATH

      - name: Export Solution
        run: |
          pac auth create --environment "${{ secrets.POWERPLATFORM_URL }}" --username "${{ secrets.USERNAME }}" --password "${{ secrets.PASSWORD }}"
          pac solution export --name ExpenseManagmentSystem --path out/ExpenseManagmentSystem.zip --overwrite

      - name: Unpack Solution
        run: |
          pac solution unpack --path out/solutions/ExpenseManagmentSystem --zipfile out/ExpenseManagmentSystem.zip --type Unmanaged --overwrite

      - name: Prepare for source control
        run: |
          echo "Solution unpacked and ready for source control."
