name: Export Power Platform Solution

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Power Platform CLI manually
      shell: pwsh
      run: |
        dotnet tool install --global Microsoft.PowerApps.CLI.Tool
        echo "$env:USERPROFILE\\.dotnet\\tools" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Export Solution
      run: |
        pac auth create --environment "${{ secrets.POWERPLATFORM_URL }}" --applicationId "${{ secrets.APP_ID }}" --clientSecret "${{ secrets.CLIENT_SECRET }}" --tenant "${{ secrets.TENANT_ID }}"
        pac solution export --name ExpenseManagmentSystem --path out/ExpenseManagmentSystem.zip
